README.md

【Commit_0000002——修改ReadMe】

---

src/business/home/home.vue
src/business/team/createTeam.vue
src/business/team/myTeam.vue
src/business/team/nearbyTeam.vue
src/business/team/teamList.vue
src/router/index.js

```
一、增加我的组件列表界面
二、增加附近队伍列表界面
三、增加新建队伍界面
```

【Commit_0000007——增加组件等截面】

---

src/business/businessCenter/businessCenterList.vue
src/business/club/clubList.vue
src/business/home/home.vue
src/business/home/stepDetails.vue
src/business/news/news.vue
src/business/news/newsDetails.vue
src/business/personalCenter/personalCenter.vue
src/business/register/forgetPassword.vue
src/business/register/register.vue
src/business/register/selectGender.vue
src/business/team/createTeam.vue
src/business/team/teamList.vue
src/business/tradingCenter/tradingCenterList.vue
src/components/headMenu.vue
src/components/index.js
src/components/selecter.vue
src/style/common.scss

```
一、将顶部菜单抽成组件，利用Vue的Slot特性进行处理
```

【Commit_0000010——顶部菜单组件化】

---

src/business/home/home.vue
src/components/footerMenu.vue

```
一、底部菜单栏组件样式调整
二、首页活跃度信息板块样式调整-兼容iPhone5代分辨率
```

【Commit_0000013——部门样式调整】

---

src/business/club/activityList.vue
src/business/club/clubCertification.vue
src/business/club/clubCertificationSuccess.vue
src/business/club/clubDetails.vue
src/business/club/clubTeams.vue
src/business/club/publishActivity.vue

【Commit_0000015——俱乐部界面提交】

---

src/router/index.js

【Commit_0000016——俱乐部丢失路由提交】

---

src/business/personalCenter/feedback.vue
src/business/personalCenter/feedbackList.vue
src/business/personalCenter/loginPassword.vue
src/business/personalCenter/personalCenter.vue
src/business/personalCenter/personalSetting.vue
src/business/personalCenter/tradingPassword.vue
src/components/footerMenu.vue
src/index.vue
src/router/index.js
src/style/common.scss

```
一、设置界面
二、交易密码界面
三、登录密码界面
四、问题反馈列表界面
五、问题提交界面
```

【Commit_0000017——个人中心-个人设置部分界面提交】

---

src/business/personalCenter/basicInformation.vue
src/business/personalCenter/candyRecords.vue
src/business/personalCenter/editAliPay.vue
src/business/personalCenter/editNick.vue
src/business/personalCenter/editSignature.vue
src/business/personalCenter/editWeChat.vue
src/business/personalCenter/feedback.vue
src/business/personalCenter/personalCenter.vue
src/business/personalCenter/vipLevel.vue
src/components/index.js
src/components/selectOption.vue
src/router/index.js

```
一、基础资料界面提交
二、基础资料-子级界面提交
三、部分样式调整
四、增加下拉组件
五、个人中心样式调整
六、糖果明细界面提交
七、会员等级界面提交
```

【Commit_0000018——个人中心-个人设置部分界面提交】

---

src/business/personalCenter/activityRecords.vue
src/business/personalCenter/contribution.vue
src/business/personalCenter/contributionRecords.vue
src/business/personalCenter/editAliPayForm.vue
src/business/personalCenter/editBankCard.vue
src/business/personalCenter/editIdCard.vue
src/business/personalCenter/editPhoneNum.vue
src/business/personalCenter/editUserName.vue
src/business/personalCenter/faceRecognition.vue
src/business/personalCenter/identityInformation.vue
src/business/personalCenter/personalCenter.vue
src/business/personalCenter/verifiedForm.vue
src/router/index.js

```
一、实名认证界面提交
二、身份信息列表界面提交
```

【Commit_0000019——个人中心-实名认证、身份信息列表界面提交】

---

src/business/personalCenter/editSignature.vue
src/business/personalCenter/feedback.vue
src/business/personalCenter/loginPassword.vue
src/business/personalCenter/tradingPassword.vue

【Commit_0000020——个人中心-輸入框樣式調整  提交】

---

src/business/personalCenter/appeal.vue
src/business/personalCenter/feedback.vue
src/business/personalCenter/paySuccess.vue
src/business/personalCenter/transaction.vue
src/business/personalCenter/transactionDetails.vue
src/router/index.js

【Commit_0000021——我的订单界面提交】

---

src/business/home/home.vue
src/business/personalCenter/addressManage.vue
src/business/personalCenter/orderCenter.vue
src/business/personalCenter/orderDetails.vue
src/business/personalCenter/personalCenter.vue
src/business/personalCenter/teamManage.vue
src/business/personalCenter/teamRecruitment.vue
src/index.vue
src/router/index.js

```
一、个人中心剩余界面提交（未含有任何事件及界面元素）
二、对应路由提交
```

【Commit_0000022——个人中心剩余界面提交及路由提交】

---

src/business/businessCenter/businessCenterList.vue

【Commit_0000026——修复界面报错】

---

src/business/tradingCenter/tradingCenterList.vue

【Commit_0000027——修复界面样式问题】

---

src/business/businessCenter/businessCenterList.vue

【Commit_0000031——商圈首页样式修复】

---

src/business/home/home.vue
src/business/team/myTeam.vue
src/business/tradingCenter/tradingCenterList.vue

```
一、队伍列表增加用户签名、当日活跃度、当日步数信息展现
二、首页环形图修改
三、交易中心提示修改、展现增加范围选项
```

【Commit_0000032——商圈首页样式修复】

---

src/business/home/home.vue
src/business/tradingCenter/tradingCenterList.vue
src/components/footerMenu.vue
src/components/selecter.vue
src/style/common.scss

```
一、顶部的信息不再一直在最上
二、交易中心的搜索改成组合式
三、底部样式调整
四、下拉选择组件样式调整
```

【Commit_0000033——交易中心、首页、组件调整】

---

src/business/tradingCenter/tradingCenterList.vue
src/components/banner.vue

```
一、交易中心调整
二、Banner增加滑动事件
```

【Commit_0000034——交易中心、Banner调整】

---

src/business/tradingCenter/tradingCenterList.vue
src/style/common.scss

```
一、交易中心按价格搜索时，增加多个输入框
二、交易中心搜索框增加 🔍  图标
三、输入框提示文本高度调整
```

【Commit_0000035——交易中心、输入框样式调整】

---

src/business/news/healthy.vue
src/business/news/industry.vue
src/business/news/news.vue
src/business/news/newsDetails.vue
src/business/news/share.vue
src/style/common.scss

【Commit_0000038——修复样式问题】

---

src/business/news/newsDetails.vue

【Commit_0000039——修复资讯详情样式问题】

---

src/business/businessCenter/businessCenterList.vue

【Commit_0000045——商圈样式修复】

---

src/business/news/articleShare.vue

【Commit_0000047——资讯分享界面处理】

---

src/business/personalCenter/teamRecruitment.vue

【Commit_0000048——团队招募界面样式修复】

---

src/business/home/home.vue

【Commit_0000049——主页弹窗样式调整】

---

src/business/personalCenter/feedback.vue

```javascript
一、修复反馈界面提交按钮位置错乱的问题
二、记录下：
let docHeight = $(document).height()
$(window).resize(function () {
if ($(document).height() < docHeight) {
$('.btn').css('position', 'static')
}
else {
$('.btn').css('position', 'absolute')
}
})
```

【Commit_0000050——修复反馈界面提交按钮位置错乱的问题】
